# Generated by Django 4.1.3 on 2022-11-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Condiciones_Iva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Detalles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Estados_Venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.BigIntegerField(blank=True, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=30, null=True)),
                ('calle', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.BigIntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=30, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Unidad_Medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_recibido', models.DateTimeField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Ventas',
                'managed': False,
            },
        ),
    ]
