# Generated by Django 4.1.2 on 2022-11-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("confApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condicionesiva",
            options={"managed": False, "verbose_name_plural": "Condiciones Iva"},
        ),
    ]
