# Generated by Django 4.1.2 on 2022-12-01 19:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('confApp', '0003_alter_detalles_options_alter_estadosventa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicionesiva',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='detalles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='estadosventa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='localidades',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'managed': False},
        ),
    ]
