# Generated by Django 4.1.2 on 2022-12-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confApp', '0004_alter_condicionesiva_options_alter_detalles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicionesiva',
            options={'managed': False, 'verbose_name_plural': 'Condiciones de Iva'},
        ),
        migrations.AlterModelOptions(
            name='detalles',
            options={'managed': False, 'verbose_name_plural': 'Detalles'},
        ),
        migrations.AlterModelOptions(
            name='estadosventa',
            options={'managed': False, 'verbose_name_plural': 'Estados de la Venta'},
        ),
        migrations.AlterModelOptions(
            name='localidades',
            options={'managed': False, 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': False, 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'managed': False, 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedida',
            options={'managed': False, 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.AlterModelOptions(
            name='ventas',
            options={'managed': False, 'verbose_name_plural': 'Ventas'},
        ),
    ]
